base_url = "https://clip-vito.vercel.app/"
[book]
title = "Vito's Clip"
description = "Vito's Clip feedId:61414424947435520+userId:58336736209433600"

src = "content"
language = "zh"
authors = ["Vito Wang"]

[output.html]
git-repository-url = "https://github.com/Vitowong00/clip"
edit-url-template = "https://github.com/Vitowong00/clip/edit/main/{path}"

[output.html.search]
enable = false

[output.markdown]
enable = true

[mail]
# false will diasble mail sending
enable = false
from_email = "vitowang@proton.com"
from_name = "Vito"
# you can set the mailjet contact list id here
# mailjet_contact_list_id = "17669"
# or directly set the to_email, seperated by comma
# or your can also set the environment variable TO_EMAIL
to_email = ""
