base_url = "https://clip-virid.vercel.app/"
[book]
title = "Vito's Clip"
description = "Vito's Clip"
src = "content"
language = "zh"
authors = ["Vito wang"]

[output.html]
git-repository-url = "https://github.com/Vitowong00/clip"
edit-url-template = "https://github.com/Vitowong00/clip/edit/main/{path}"

[output.html.search]
enable = false

[output.markdown]
enable = true

[mail]
# false will diasble mail sending
enable = false
from_email = "vitowang@proton.com"
from_name = "Vito"
# you can set the mailjet contact list id here
# mailjet_contact_list_id = "17669"
# or directly set the to_email, seperated by comma
# or your can also set the environment variable TO_EMAIL
to_email = ""
